//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.CollectionOrPayRecord {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblOID;
	protected global::System.Web.UI.WebControls.Label lblExp_OID;
	protected global::System.Web.UI.WebControls.Label lblExp_OID2;
	protected global::System.Web.UI.WebControls.Label lblTradeDate;
	protected global::System.Web.UI.WebControls.Label lblMoney;
	protected global::System.Web.UI.WebControls.Label lblAuditor;
	protected global::System.Web.UI.WebControls.Label lblauditState;
	protected global::System.Web.UI.WebControls.Label lblOperator;
	protected global::System.Web.UI.WebControls.Label lblInvoice;
	protected global::System.Web.UI.WebControls.Label lblDescription;


       
    }
}
