//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.ExpectPayAccount {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtOID;
		protected global::System.Web.UI.WebControls.TextBox txtIdent;
		protected global::System.Web.UI.WebControls.TextBox txtDescription;
		protected global::System.Web.UI.WebControls.TextBox txtCreationDate;
		protected global::System.Web.UI.WebControls.TextBox txtLender;
		protected global::System.Web.UI.WebControls.TextBox txtLoaned;
		protected global::System.Web.UI.WebControls.TextBox txtModifyUser;
		protected global::System.Web.UI.WebControls.TextBox txtPayReason;
		protected global::System.Web.UI.WebControls.TextBox txtAuditor;
		protected global::System.Web.UI.WebControls.TextBox txtOperator;
		protected global::System.Web.UI.WebControls.TextBox txtGetMoneyPerson;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
