//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.IngredientCompoent {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblOID;
		protected global::System.Web.UI.WebControls.TextBox txtPro_OID;
		protected global::System.Web.UI.WebControls.TextBox txtDis_OID;
		protected global::System.Web.UI.WebControls.TextBox txtRec_OID;
		protected global::System.Web.UI.WebControls.TextBox txtIngredientCategory;
		protected global::System.Web.UI.WebControls.TextBox txt数量;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
