//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.IngredientCompoent {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblOID;
	protected global::System.Web.UI.WebControls.Label lblPro_OID;
	protected global::System.Web.UI.WebControls.Label lblDis_OID;
	protected global::System.Web.UI.WebControls.Label lblRec_OID;
	protected global::System.Web.UI.WebControls.Label lblIngredientCategory;
	protected global::System.Web.UI.WebControls.Label lbl数量;


       
    }
}
