//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Receival {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblOID;
	protected global::System.Web.UI.WebControls.Label lblIdent;
	protected global::System.Web.UI.WebControls.Label lblName;
	protected global::System.Web.UI.WebControls.Label lblDescription;
	protected global::System.Web.UI.WebControls.Label lblauditState;
	protected global::System.Web.UI.WebControls.Label lblReceivalState;
	protected global::System.Web.UI.WebControls.Label lblFinishReceiptDate;
	protected global::System.Web.UI.WebControls.Label lblCreationDate;
	protected global::System.Web.UI.WebControls.Label lblAuditor;
	protected global::System.Web.UI.WebControls.Label lblOperator;


       
    }
}
